import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const AppSettingsContext = createContext(null);

const messages = {
  en: {
    languageName: 'English',
    switchLanguage: 'বাংলা',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeSystem: 'System',
    installApp: 'Install app',
    installed: 'Installed',
    menu: 'Menu',
    online: 'Online',
    offline: 'Offline',
    queued: 'queued',
    appTitle: 'ANTI-KUDDUS PROTOCOL',
    navLabel: 'Protocol modules',
    navOverview: 'Overview',
    navWhistleblower: 'Whistleblower',
    navSeats: 'Seat Planner',
    navSyllabus: 'Syllabus AI',
    navLedger: 'Tiffin Ledger',
    navSos: 'SOS Flare',
    navFacts: 'Fact-Checker',
    navCaptain: 'Captain Board',
    navChecklist: 'Submission Check',
    anonymousStudent: 'Anonymous student',
    captainAccess: 'Captain access',
    systemOperational: 'System operational',
    systemOfflineReady: 'Offline help ready',
    logout: 'Log out',
    baselineComplete: 'Junior baseline complete',
    builtFor: 'Built for Class 7 · Section B',
    eventName: 'BAIUST CSE Spring Fest 2026',
    welcome: 'Welcome, {name}.',
    offlineSosSynced: '{count} offline SOS alert(s) sent.',
    loginClass: 'Class 7 · Section B',
    loginHero: 'Three strikes.\nOne fair classroom.',
    loginHeroDescription: 'A private accountability hub built for students, Biltu, Miltu, and one very tired class teacher.',
    anonymousReports: 'Anonymous reports',
    serverAccess: 'Server-side access',
    roleDashboard: 'Role-aware dashboard',
    secureEntry: 'Secure entry',
    studentLogin: 'Student whistleblower login',
    captainLogin: 'Captain command login',
    studentLoginText: 'Your roll is checked against the private class mapping. It is never saved with a complaint.',
    captainLoginText: 'For Biltu and Miltu to review alerts and anonymous reports.',
    student: 'Student',
    captain: 'Captain',
    secretRoll: 'Secret class roll',
    captainCode: 'Captain access code',
    exampleRoll: 'Example: 701',
    enterCode: 'Enter access code',
    showHide: 'Show or hide value',
    checking: 'Checking access…',
    enterProtocol: 'Enter protocol',
    demoRolls: 'Demo student rolls',
    enterSecretRoll: 'Enter your secret class roll.',
    enterCaptainCode: 'Enter the captain access code.',
    commandCentre: 'Command centre',
    studentDashboard: 'Student protection dashboard',
    captainDashboard: 'Captain oversight dashboard',
    studentDashboardDescription: 'Every required junior mission is available from one protected workspace.',
    captainDashboardDescription: 'Review the protocol status, distress signals, and anonymous evidence.',
    totalReports: 'Total reports',
    anonymousComplaintLog: 'Anonymous complaint log',
    cashRecorded: 'Cash recorded',
    forcedPayments: 'Forced payments',
    tiffinsTaken: 'Tiffins taken',
    foodItemsLogged: 'Food items logged',
    activeSos: 'Active SOS',
    needsAttention: 'Needs captain attention',
    noDistress: 'No current distress',
    requiredModules: 'Required junior modules',
    sixMissions: 'Six missions, one ecosystem',
    implemented: '6/6 implemented',
    openModule: 'Open module →',
    studentOnly: 'Student-only action. Use a student login to test this module.',
    viewStudent: 'View from student login',
    mission01: 'Mission 01',
    mission02: 'Mission 02',
    mission03: 'Mission 03',
    mission04: 'Mission 04',
    mission05: 'Mission 05',
    mission06: 'Mission 06',
    m1Title: 'Anonymous Whistleblower',
    m1Text: 'Submit a categorized complaint without attaching your roll to the report.',
    m2Title: 'Seat Planner',
    m2Text: 'Generate a front-to-back classroom grid sorted by student height.',
    m3Title: 'Syllabus Negotiator',
    m3Text: 'Turn an oversized syllabus into a clean list of examinable topics.',
    m4Title: 'Tiffin Ledger',
    m4Text: 'Track forced payments and stolen food with visual totals over time.',
    m5Title: 'SOS Rescue Flare',
    m5Text: 'Send a location-based distress signal from any school device.',
    m6Title: 'Rulebook Fact-Checker',
    m6Text: 'Match Kuddus’s claims against pre-seeded official school rules.',
    impeachmentTracker: 'Impeachment tracker',
    protocolComplete: 'Protocol complete',
    warnings: 'Warnings: {count}/3',
    impeached: 'IMPEACHED',
    strikesLeft: '{count} left',
    threeReached: 'Three legitimate complaints have reached Rashid Sir.',
    complaintsRemaining: '{count} legitimate complaint(s) remaining.',
    complaintDescription: 'Authenticate with a roll, submit without attaching that roll, and move the class toward three legitimate strikes.',
    logIncident: 'Log an incident',
    incidentHelp: 'Use factual details. Do not include your own name or roll.',
    complaintCategory: 'Complaint category',
    description: 'Description',
    complaintPlaceholder: 'Describe what happened, where it happened, and what Kuddus did…',
    minCharacters: 'Minimum 8 characters',
    delivering: 'Delivering securely…',
    submitComplaint: 'Submit anonymous complaint',
    privacyDesign: 'Privacy design',
    privacySubtitle: 'Baseline-safe and easy to explain.',
    privacy1: 'Roll validation happens only on the server.',
    privacy2: 'Complaint rows do not contain roll numbers.',
    privacy3: 'The dashboard displays totals, not identities.',
    categoryTiffin: 'Tiffin Theft',
    categoryBribes: 'Bribes',
    categorySyllabus: 'Syllabus Bloat',
    categorySports: 'Unfair Sports',
    categoryWashroom: 'Washroom Toll',
    categoryOther: 'Other',
    seatDescription: 'Input student records, choose an N × M layout, and place shorter students from the front row toward taller students at the back.',
    studentRecords: 'Student records',
    studentRecordsText: 'Name, roll, and height are required.',
    studentName: 'Student name',
    roll: 'Roll',
    heightCm: 'Height cm',
    addStudent: 'Add student',
    removeStudent: 'Remove {name}',
    resetDemo: 'Reset demo list',
    classroomGrid: 'Classroom grid',
    classroomGridText: 'Front row appears closest to the teacher.',
    rows: 'Rows',
    columns: 'Columns',
    teacherPodium: 'Rashid Sir · Teacher’s podium',
    frontRow: 'Front row',
    rowNumber: 'Row {count}',
    emptyDesk: 'Empty desk',
    availableSeat: 'Available seat',
    studentsDoNotFit: '{count} student(s) do not fit. Increase rows or columns.',
    shorterFront: 'Shorter students begin at the front',
    tallerBack: 'Taller students move toward the back',
    invalidStudent: 'Enter a valid name, roll, and height between 80–230 cm.',
    duplicateRoll: 'That roll already exists in the list.',
    studentAdded: 'Student added to the seating list.',
    syllabusDescription: 'A server-side Gemini integration filters long syllabus statements into a short, student-friendly topic list.',
    pasteSyllabus: 'Paste Kuddus’s syllabus',
    syllabusLimit: 'Long-form text is accepted up to 6,000 characters.',
    loadDemo: 'Load demo',
    negotiating: 'Negotiating syllabus…',
    summarizeAi: 'Summarize with AI',
    cleanTopics: 'Clean topic list',
    liveGemini: 'Live Gemini API result',
    localDemo: 'Local fallback demonstration',
    resultAppears: 'Your filtered result will appear here.',
    copyResult: 'Copy result',
    noSummary: 'No summary yet',
    noSummaryText: 'Paste a syllabus and run the negotiator.',
    geminiGenerated: 'Gemini summary generated.',
    demoGenerated: 'Demo summary generated. Add an API key for live AI.',
    copied: 'Summary copied to clipboard.',
    ledgerDescription: 'Anonymous records are stored in SQLite and visualized as cash and food totals over time.',
    totalPayments: 'Total forced payments',
    acrossEntries: 'Recorded across all entries',
    totalTiffins: 'Total stolen tiffins',
    foodRecorded: 'Food items recorded',
    addEntry: 'Add anonymous entry',
    noRollStored: 'No roll number is stored with this record.',
    forcedPayment: 'Forced payment',
    stolenTiffin: 'Stolen tiffin',
    amountTaka: 'Amount in Taka',
    foodItem: 'Food item',
    foodPlaceholder: 'Fried rice, sandwich…',
    quantity: 'Quantity',
    saving: 'Saving…',
    saveEntry: 'Save ledger entry',
    timeline: 'Extortion timeline',
    timelineText: 'Daily cash and food records from the ledger.',
    cashExtorted: 'Cash extorted (৳)',
    foodItems: 'Food items',
    recentEntries: 'Recent anonymous entries',
    latestRecords: 'Latest records from the relational database.',
    type: 'Type',
    details: 'Details',
    loggedAt: 'Logged at',
    payment: 'Payment',
    food: 'Food',
    ledgerSaved: 'Anonymous ledger entry saved.',
    sosDescription: 'A mobile-first panic action sends the selected school location to the central captain dashboard.',
    emergencyChannel: 'Emergency channel',
    signalDelivered: 'Signal delivered',
    needBackup: 'Need immediate backup?',
    signalText: 'Biltu and Miltu can now see an active alert from {location}.',
    selectAndSend: 'Select your current location, then press and confirm the SOS button.',
    sending: 'SENDING…',
    sendAgain: 'SEND AGAIN',
    sendSos: 'SEND SOS',
    locationTimeOnly: 'Only the selected location and time are recorded.',
    whatNext: 'What happens next',
    phoneReady: 'Designed for quick use on a phone.',
    selectLocation: 'Select location',
    nearestArea: 'Choose the nearest known school area.',
    sendSignal: 'Send the signal',
    serverCreates: 'The server creates an active distress record.',
    captainResponds: 'Captain responds',
    captainResolves: 'Biltu or Miltu marks the alert resolved.',
    offlineHelp: 'Offline emergency help',
    offlineHelpText: 'Contacts and safety steps remain available without internet.',
    connection: 'Connection',
    queueCount: 'Offline SOS queue: {count}',
    offlineQueueNotice: 'No internet. Your SOS was saved on this device and will send automatically when the connection returns.',
    saveContacts: 'Save emergency contacts',
    contactsSaved: 'Emergency contacts saved on this device.',
    contactName: 'Contact name',
    phoneNumber: 'Phone number',
    call: 'Call',
    contact1: 'School office',
    contact2: 'Guardian',
    contact3: 'Class teacher',
    noNumber: 'Add a phone number first.',
    safetySteps: 'Offline safety steps',
    safety1: 'Move toward a teacher, office, or crowded safe area.',
    safety2: 'Call a trusted adult using a saved contact.',
    safety3: 'Keep the queued SOS; it will sync when internet returns.',
    queuedOffline: 'SOS saved offline. It will send automatically later.',
    locationLibrary: 'Library',
    locationPlayground: 'Playground',
    locationCorridor: 'Corridor',
    locationClassroom: 'Classroom',
    locationCanteen: 'Canteen',
    locationWashroom: 'Washroom',
    locationGate: 'School Gate',
    factsDescription: 'Search a pre-seeded SQLite rulebook using direct string and keyword matching—the exact junior baseline requirement.',
    claimPlaceholder: 'Type a claim made by Kuddus…',
    searching: 'Searching…',
    checkRulebook: 'Check rulebook',
    example: 'Example {count}',
    officialRule: 'Official matching rule',
    matchedKeywords: 'Matched keywords: {keywords}',
    noRule: 'No matching rule',
    noRuleText: 'Try simpler words such as homework, washroom, food, money, or captain.',
    readyVerify: 'Ready to verify',
    readyVerifyText: 'Enter a claim and search the official school guidelines.',
    noExactMatch: 'No exact keyword match was found.',
    captainBoardDescription: 'The page refreshes its data every five seconds to surface new distress signals and anonymous complaints.',
    refreshNow: 'Refresh now',
    loadingCommand: 'Loading command data…',
    distressSignals: 'Active distress signals',
    alertsNeedAttention: '{count} alert(s) currently need attention.',
    liveSos: 'LIVE SOS',
    markResolved: 'Mark resolved',
    allClear: 'All clear',
    noActiveSignals: 'No active distress signals.',
    complaintFeed: 'Anonymous complaint feed',
    rollsAbsent: 'Roll numbers are intentionally absent from every record.',
    alertResolved: 'SOS alert resolved.',
    submissionReadiness: 'Submission readiness',
    juniorChecklist: 'Junior feature checklist',
    checklistDescription: 'The implementation covers every required baseline item. The final GitHub push and video remain team submission tasks.',
    implementedLabel: 'Implemented',
    teamAction: 'Team action',
    githubText: 'Push the project folder. The included .gitignore prevents .env and database files from being uploaded.',
    readmeText: 'Setup, technology choices, database design, security notes, and demo credentials are included.',
    videoText: 'Show login, all six missions, the captain board, and the three-strike state in one short walkthrough.',
    rowM1: 'Roll-number login, complaint form, dynamic X/3 strike bar',
    rowM2: 'Name/roll/height input and N × M height-sorted desk grid',
    rowM3: 'LLM API integration with clean bulleted syllabus output',
    rowM4: 'Anonymous payment/tiffin ledger and chart over time',
    rowM5: 'Mobile SOS button, location dropdown, captain dashboard',
    rowM6: 'String-matching search over pre-seeded relational rules',
    rowDocs: 'README with setup, architecture, trade-offs, and screenshots',
    rowSubmit: 'GitHub repository and recorded walkthrough',
    pwaReady: 'Installable mobile PWA',
    pwaReadyText: 'Install from Chrome and use the app in a standalone mobile window.',
    offlineReady: 'Offline SOS queue',
    offlineReadyText: 'Important SOS actions are saved locally when the network is unavailable.',
    bilingualReady: 'Bangla and English',
    bilingualReadyText: 'Users can switch the full interface language at any time.',
    themeReady: 'Light and dark themes',
    themeReadyText: 'The selected appearance is remembered on the device.'
  },
  bn: {
    languageName: 'বাংলা',
    switchLanguage: 'English',
    themeLight: 'লাইট',
    themeDark: 'ডার্ক',
    themeSystem: 'সিস্টেম',
    installApp: 'অ্যাপ ইনস্টল',
    installed: 'ইনস্টল করা আছে',
    menu: 'মেনু',
    online: 'অনলাইন',
    offline: 'অফলাইন',
    queued: 'অপেক্ষমাণ',
    appTitle: 'অ্যান্টি-কুদ্দুস প্রোটোকল',
    navLabel: 'প্রোটোকল মডিউল',
    navOverview: 'ওভারভিউ',
    navWhistleblower: 'গোপন অভিযোগ',
    navSeats: 'সিট প্ল্যানার',
    navSyllabus: 'সিলেবাস AI',
    navLedger: 'টিফিন লেজার',
    navSos: 'SOS সহায়তা',
    navFacts: 'নিয়ম যাচাই',
    navCaptain: 'ক্যাপ্টেন বোর্ড',
    navChecklist: 'সাবমিশন চেক',
    anonymousStudent: 'পরিচয়-গোপন শিক্ষার্থী',
    captainAccess: 'ক্যাপ্টেন অ্যাক্সেস',
    systemOperational: 'সিস্টেম সচল আছে',
    systemOfflineReady: 'অফলাইন সহায়তা প্রস্তুত',
    logout: 'লগ আউট',
    baselineComplete: 'জুনিয়র বেসলাইন সম্পূর্ণ',
    builtFor: 'ক্লাস ৭ · সেকশন বি-এর জন্য তৈরি',
    eventName: 'BAIUST CSE Spring Fest 2026',
    welcome: 'স্বাগতম, {name}।',
    offlineSosSynced: '{count}টি অফলাইন SOS পাঠানো হয়েছে।',
    loginClass: 'ক্লাস ৭ · সেকশন বি',
    loginHero: 'তিনটি স্ট্রাইক।\nএকটি ন্যায্য ক্লাসরুম।',
    loginHeroDescription: 'শিক্ষার্থী, বিল্টু, মিল্টু এবং ক্লান্ত রাশিদ স্যারের জন্য একটি নিরাপদ জবাবদিহি ব্যবস্থা।',
    anonymousReports: 'পরিচয়-গোপন অভিযোগ',
    serverAccess: 'সার্ভার-নিয়ন্ত্রিত অ্যাক্সেস',
    roleDashboard: 'ভূমিকা অনুযায়ী ড্যাশবোর্ড',
    secureEntry: 'নিরাপদ প্রবেশ',
    studentLogin: 'শিক্ষার্থীর গোপন লগইন',
    captainLogin: 'ক্যাপ্টেন কমান্ড লগইন',
    studentLoginText: 'আপনার রোল গোপন ক্লাস তালিকার সঙ্গে যাচাই করা হয়। কোনো অভিযোগের সঙ্গে রোল সংরক্ষণ করা হয় না।',
    captainLoginText: 'বিল্টু ও মিল্টু এখান থেকে সতর্কতা এবং গোপন অভিযোগ দেখবে।',
    student: 'শিক্ষার্থী',
    captain: 'ক্যাপ্টেন',
    secretRoll: 'গোপন ক্লাস রোল',
    captainCode: 'ক্যাপ্টেন অ্যাক্সেস কোড',
    exampleRoll: 'উদাহরণ: 701',
    enterCode: 'অ্যাক্সেস কোড লিখুন',
    showHide: 'লেখা দেখান বা লুকান',
    checking: 'যাচাই হচ্ছে…',
    enterProtocol: 'প্রোটোকলে প্রবেশ করুন',
    demoRolls: 'ডেমো শিক্ষার্থী রোল',
    enterSecretRoll: 'আপনার গোপন ক্লাস রোল লিখুন।',
    enterCaptainCode: 'ক্যাপ্টেন অ্যাক্সেস কোড লিখুন।',
    commandCentre: 'কমান্ড সেন্টার',
    studentDashboard: 'শিক্ষার্থী নিরাপত্তা ড্যাশবোর্ড',
    captainDashboard: 'ক্যাপ্টেন পর্যবেক্ষণ ড্যাশবোর্ড',
    studentDashboardDescription: 'একটি নিরাপদ জায়গা থেকে জুনিয়রদের প্রয়োজনীয় সব মিশন ব্যবহার করা যাবে।',
    captainDashboardDescription: 'প্রোটোকলের অবস্থা, বিপদ সংকেত এবং গোপন প্রমাণ দেখুন।',
    totalReports: 'মোট অভিযোগ',
    anonymousComplaintLog: 'গোপন অভিযোগের হিসাব',
    cashRecorded: 'রেকর্ড করা টাকা',
    forcedPayments: 'জোর করে নেওয়া টাকা',
    tiffinsTaken: 'নেওয়া টিফিন',
    foodItemsLogged: 'রেকর্ড করা খাবার',
    activeSos: 'সক্রিয় SOS',
    needsAttention: 'ক্যাপ্টেনের নজর দরকার',
    noDistress: 'এখন কোনো বিপদ নেই',
    requiredModules: 'জুনিয়রদের প্রয়োজনীয় মডিউল',
    sixMissions: 'ছয়টি মিশন, একটি সম্পূর্ণ সিস্টেম',
    implemented: '৬/৬ সম্পন্ন',
    openModule: 'মডিউল খুলুন →',
    studentOnly: 'এটি শুধু শিক্ষার্থীর কাজ। পরীক্ষা করতে শিক্ষার্থী হিসেবে লগইন করুন।',
    viewStudent: 'শিক্ষার্থী লগইন থেকে দেখুন',
    mission01: 'মিশন ০১',
    mission02: 'মিশন ০২',
    mission03: 'মিশন ০৩',
    mission04: 'মিশন ০৪',
    mission05: 'মিশন ০৫',
    mission06: 'মিশন ০৬',
    m1Title: 'গোপন অভিযোগ ব্যবস্থা',
    m1Text: 'অভিযোগের সঙ্গে রোল নম্বর না রেখে বিভাগ অনুযায়ী অভিযোগ জমা দিন।',
    m2Title: 'সিট প্ল্যানার',
    m2Text: 'উচ্চতা অনুযায়ী সামনে থেকে পেছনে সাজানো ক্লাসরুম গ্রিড তৈরি করুন।',
    m3Title: 'সিলেবাস নেগোশিয়েটর',
    m3Text: 'অতিরিক্ত বড় সিলেবাসকে পরীক্ষার উপযোগী পরিষ্কার বিষয়ের তালিকায় রূপান্তর করুন।',
    m4Title: 'টিফিন লেজার',
    m4Text: 'জোর করে নেওয়া টাকা ও চুরি হওয়া খাবার সময় অনুযায়ী চার্টে দেখুন।',
    m5Title: 'SOS উদ্ধার সংকেত',
    m5Text: 'স্কুলের যেকোনো স্থান থেকে অবস্থানসহ বিপদ সংকেত পাঠান।',
    m6Title: 'স্কুলের নিয়ম যাচাই',
    m6Text: 'কুদ্দুসের দাবিকে সংরক্ষিত অফিসিয়াল স্কুল নিয়মের সঙ্গে মিলিয়ে দেখুন।',
    impeachmentTracker: 'ইমপিচমেন্ট ট্র্যাকার',
    protocolComplete: 'প্রোটোকল সম্পূর্ণ',
    warnings: 'সতর্কতা: {count}/৩',
    impeached: 'ইমপিচড',
    strikesLeft: 'আর {count}টি',
    threeReached: 'তিনটি বৈধ অভিযোগ রাশিদ স্যারের কাছে পৌঁছেছে।',
    complaintsRemaining: 'আর {count}টি বৈধ অভিযোগ প্রয়োজন।',
    complaintDescription: 'রোল দিয়ে লগইন করুন, রোল সংযুক্ত না করে অভিযোগ দিন এবং তিনটি বৈধ স্ট্রাইকের দিকে এগিয়ে যান।',
    logIncident: 'ঘটনা লিখুন',
    incidentHelp: 'সত্য তথ্য লিখুন। নিজের নাম বা রোল লিখবেন না।',
    complaintCategory: 'অভিযোগের ধরন',
    description: 'বিবরণ',
    complaintPlaceholder: 'কী ঘটেছে, কোথায় ঘটেছে এবং কুদ্দুস কী করেছে তা লিখুন…',
    minCharacters: 'সর্বনিম্ন ৮ অক্ষর',
    delivering: 'নিরাপদভাবে পাঠানো হচ্ছে…',
    submitComplaint: 'গোপন অভিযোগ জমা দিন',
    privacyDesign: 'গোপনীয়তার ব্যবস্থা',
    privacySubtitle: 'নিরাপদ এবং সহজে ব্যাখ্যা করা যায়।',
    privacy1: 'রোল যাচাই শুধু সার্ভারে হয়।',
    privacy2: 'অভিযোগের রেকর্ডে রোল নম্বর থাকে না।',
    privacy3: 'ড্যাশবোর্ডে পরিচয় নয়, শুধু মোট হিসাব দেখায়।',
    categoryTiffin: 'টিফিন চুরি',
    categoryBribes: 'ঘুষ',
    categorySyllabus: 'অতিরিক্ত সিলেবাস',
    categorySports: 'অন্যায্য খেলাধুলা',
    categoryWashroom: 'ওয়াশরুম টোল',
    categoryOther: 'অন্যান্য',
    seatDescription: 'শিক্ষার্থীর তথ্য দিন, N × M গ্রিড বেছে নিন এবং খাটো শিক্ষার্থী সামনে ও লম্বা শিক্ষার্থী পেছনে বসান।',
    studentRecords: 'শিক্ষার্থীর তথ্য',
    studentRecordsText: 'নাম, রোল এবং উচ্চতা দিতে হবে।',
    studentName: 'শিক্ষার্থীর নাম',
    roll: 'রোল',
    heightCm: 'উচ্চতা (সেমি)',
    addStudent: 'শিক্ষার্থী যোগ করুন',
    removeStudent: '{name}-কে বাদ দিন',
    resetDemo: 'ডেমো তালিকা পুনরায় আনুন',
    classroomGrid: 'ক্লাসরুম গ্রিড',
    classroomGridText: 'সামনের সারিটি শিক্ষকের সবচেয়ে কাছে।',
    rows: 'সারি',
    columns: 'কলাম',
    teacherPodium: 'রাশিদ স্যার · শিক্ষকের স্থান',
    frontRow: 'সামনের সারি',
    rowNumber: '{count} নম্বর সারি',
    emptyDesk: 'খালি ডেস্ক',
    availableSeat: 'খালি আসন',
    studentsDoNotFit: '{count} জন শিক্ষার্থীর জায়গা হচ্ছে না। সারি বা কলাম বাড়ান।',
    shorterFront: 'খাটো শিক্ষার্থী সামনে থাকবে',
    tallerBack: 'লম্বা শিক্ষার্থী পেছনের দিকে যাবে',
    invalidStudent: 'সঠিক নাম, রোল এবং ৮০–২৩০ সেমির মধ্যে উচ্চতা দিন।',
    duplicateRoll: 'এই রোল তালিকায় আগে থেকেই আছে।',
    studentAdded: 'শিক্ষার্থীকে সিট তালিকায় যোগ করা হয়েছে।',
    syllabusDescription: 'সার্ভার-সাইড Gemini বড় সিলেবাস থেকে ছোট ও সহজ বিষয়ের তালিকা তৈরি করে।',
    pasteSyllabus: 'কুদ্দুসের সিলেবাস লিখুন',
    syllabusLimit: 'সর্বোচ্চ ৬,০০০ অক্ষরের লেখা দেওয়া যাবে।',
    loadDemo: 'ডেমো লিখুন',
    negotiating: 'সিলেবাস ছোট করা হচ্ছে…',
    summarizeAi: 'AI দিয়ে সংক্ষেপ করুন',
    cleanTopics: 'পরিষ্কার বিষয়ের তালিকা',
    liveGemini: 'সরাসরি Gemini API-এর ফলাফল',
    localDemo: 'লোকাল ডেমো ফলাফল',
    resultAppears: 'সংক্ষিপ্ত ফলাফল এখানে দেখা যাবে।',
    copyResult: 'ফলাফল কপি করুন',
    noSummary: 'এখনো কোনো সারাংশ নেই',
    noSummaryText: 'সিলেবাস লিখে নেগোশিয়েটর চালু করুন।',
    geminiGenerated: 'Gemini সারাংশ তৈরি হয়েছে।',
    demoGenerated: 'ডেমো সারাংশ তৈরি হয়েছে। লাইভ AI-এর জন্য API key যোগ করুন।',
    copied: 'সারাংশ কপি করা হয়েছে।',
    ledgerDescription: 'গোপন রেকর্ড SQLite-এ রাখা হয় এবং টাকা ও খাবারের হিসাব চার্টে দেখানো হয়।',
    totalPayments: 'মোট জোর করে নেওয়া টাকা',
    acrossEntries: 'সব রেকর্ড মিলিয়ে',
    totalTiffins: 'মোট চুরি হওয়া টিফিন',
    foodRecorded: 'রেকর্ড করা খাবার',
    addEntry: 'গোপন রেকর্ড যোগ করুন',
    noRollStored: 'এই রেকর্ডের সঙ্গে কোনো রোল রাখা হয় না।',
    forcedPayment: 'জোর করে টাকা নেওয়া',
    stolenTiffin: 'চুরি হওয়া টিফিন',
    amountTaka: 'টাকার পরিমাণ',
    foodItem: 'খাবারের নাম',
    foodPlaceholder: 'ফ্রাইড রাইস, স্যান্ডউইচ…',
    quantity: 'পরিমাণ',
    saving: 'সংরক্ষণ হচ্ছে…',
    saveEntry: 'লেজার রেকর্ড সংরক্ষণ করুন',
    timeline: 'চাঁদাবাজির সময়ভিত্তিক চার্ট',
    timelineText: 'লেজারে প্রতিদিনের টাকা ও খাবারের হিসাব।',
    cashExtorted: 'নেওয়া টাকা (৳)',
    foodItems: 'খাবারের সংখ্যা',
    recentEntries: 'সাম্প্রতিক গোপন রেকর্ড',
    latestRecords: 'রিলেশনাল ডাটাবেসের সর্বশেষ রেকর্ড।',
    type: 'ধরন',
    details: 'বিস্তারিত',
    loggedAt: 'রেকর্ডের সময়',
    payment: 'টাকা',
    food: 'খাবার',
    ledgerSaved: 'গোপন লেজার রেকর্ড সংরক্ষণ হয়েছে।',
    sosDescription: 'মোবাইল-বান্ধব প্যানিক বাটন নির্বাচিত স্কুল লোকেশন ক্যাপ্টেন ড্যাশবোর্ডে পাঠায়।',
    emergencyChannel: 'জরুরি চ্যানেল',
    signalDelivered: 'সংকেত পৌঁছেছে',
    needBackup: 'এখনই সাহায্য দরকার?',
    signalText: 'বিল্টু ও মিল্টু এখন {location} থেকে সক্রিয় সতর্কতা দেখতে পারবে।',
    selectAndSend: 'আপনার বর্তমান স্থান বেছে নিয়ে SOS বাটন চাপুন।',
    sending: 'পাঠানো হচ্ছে…',
    sendAgain: 'আবার পাঠান',
    sendSos: 'SOS পাঠান',
    locationTimeOnly: 'শুধু নির্বাচিত স্থান ও সময় রেকর্ড করা হয়।',
    whatNext: 'এরপর কী হবে',
    phoneReady: 'ফোনে দ্রুত ব্যবহারের জন্য তৈরি।',
    selectLocation: 'স্থান নির্বাচন করুন',
    nearestArea: 'নিকটবর্তী পরিচিত স্কুল এলাকা বেছে নিন।',
    sendSignal: 'সংকেত পাঠান',
    serverCreates: 'সার্ভার একটি সক্রিয় বিপদ রেকর্ড তৈরি করে।',
    captainResponds: 'ক্যাপ্টেন ব্যবস্থা নেয়',
    captainResolves: 'বিল্টু বা মিল্টু সতর্কতাটি সমাধান হয়েছে বলে চিহ্নিত করে।',
    offlineHelp: 'অফলাইন জরুরি সহায়তা',
    offlineHelpText: 'ইন্টারনেট না থাকলেও যোগাযোগ ও নিরাপত্তা নির্দেশনা পাওয়া যাবে।',
    connection: 'সংযোগ',
    queueCount: 'অফলাইন SOS অপেক্ষমাণ: {count}',
    offlineQueueNotice: 'ইন্টারনেট নেই। SOS এই ডিভাইসে সংরক্ষিত হয়েছে এবং নেট এলে স্বয়ংক্রিয়ভাবে পাঠানো হবে।',
    saveContacts: 'জরুরি যোগাযোগ সংরক্ষণ করুন',
    contactsSaved: 'জরুরি যোগাযোগ এই ডিভাইসে সংরক্ষণ হয়েছে।',
    contactName: 'যোগাযোগের নাম',
    phoneNumber: 'ফোন নম্বর',
    call: 'কল করুন',
    contact1: 'স্কুল অফিস',
    contact2: 'অভিভাবক',
    contact3: 'ক্লাস শিক্ষক',
    noNumber: 'আগে একটি ফোন নম্বর যোগ করুন।',
    safetySteps: 'অফলাইন নিরাপত্তা ধাপ',
    safety1: 'কোনো শিক্ষক, অফিস বা লোকজন আছে এমন নিরাপদ স্থানে যান।',
    safety2: 'সংরক্ষিত যোগাযোগ থেকে বিশ্বস্ত বড় কাউকে কল করুন।',
    safety3: 'SOS অপেক্ষমাণ রাখুন; ইন্টারনেট এলে এটি নিজে থেকে পাঠাবে।',
    queuedOffline: 'SOS অফলাইনে সংরক্ষণ হয়েছে। পরে স্বয়ংক্রিয়ভাবে পাঠানো হবে।',
    locationLibrary: 'লাইব্রেরি',
    locationPlayground: 'খেলার মাঠ',
    locationCorridor: 'করিডর',
    locationClassroom: 'ক্লাসরুম',
    locationCanteen: 'ক্যান্টিন',
    locationWashroom: 'ওয়াশরুম',
    locationGate: 'স্কুল গেট',
    factsDescription: 'সরাসরি শব্দ ও কীওয়ার্ড মিলিয়ে আগে থেকে সংরক্ষিত SQLite নিয়মের টেবিল অনুসন্ধান করা হয়।',
    claimPlaceholder: 'কুদ্দুসের বলা কোনো দাবি লিখুন…',
    searching: 'খোঁজা হচ্ছে…',
    checkRulebook: 'নিয়মের বই যাচাই করুন',
    example: 'উদাহরণ {count}',
    officialRule: 'মিল পাওয়া অফিসিয়াল নিয়ম',
    matchedKeywords: 'মিল পাওয়া কীওয়ার্ড: {keywords}',
    noRule: 'কোনো নিয়ম পাওয়া যায়নি',
    noRuleText: 'বাড়ির কাজ, ওয়াশরুম, খাবার, টাকা অথবা ক্যাপ্টেনের মতো সহজ শব্দ লিখুন।',
    readyVerify: 'যাচাইয়ের জন্য প্রস্তুত',
    readyVerifyText: 'দাবি লিখে অফিসিয়াল স্কুল নিয়মে খুঁজুন।',
    noExactMatch: 'সরাসরি কীওয়ার্ডের মিল পাওয়া যায়নি।',
    captainBoardDescription: 'নতুন বিপদ সংকেত ও গোপন অভিযোগ দেখানোর জন্য প্রতি পাঁচ সেকেন্ডে তথ্য আপডেট হয়।',
    refreshNow: 'এখন আপডেট করুন',
    loadingCommand: 'কমান্ড তথ্য লোড হচ্ছে…',
    distressSignals: 'সক্রিয় বিপদ সংকেত',
    alertsNeedAttention: '{count}টি সতর্কতায় এখন ব্যবস্থা নেওয়া দরকার।',
    liveSos: 'লাইভ SOS',
    markResolved: 'সমাধান হয়েছে',
    allClear: 'সব ঠিক আছে',
    noActiveSignals: 'কোনো সক্রিয় বিপদ সংকেত নেই।',
    complaintFeed: 'গোপন অভিযোগের তালিকা',
    rollsAbsent: 'কোনো রেকর্ডেই রোল নম্বর রাখা হয়নি।',
    alertResolved: 'SOS সতর্কতা সমাধান হয়েছে।',
    submissionReadiness: 'সাবমিশন প্রস্তুতি',
    juniorChecklist: 'জুনিয়র ফিচার চেকলিস্ট',
    checklistDescription: 'সব প্রয়োজনীয় বেসলাইন ফিচার তৈরি হয়েছে। শেষ GitHub push এবং ভিডিও টিমকে জমা দিতে হবে।',
    implementedLabel: 'সম্পন্ন',
    teamAction: 'টিমের কাজ',
    githubText: 'প্রজেক্ট ফোল্ডার GitHub-এ push করুন। .gitignore ফাইল .env ও database আপলোড হতে দেবে না।',
    readmeText: 'সেটআপ, প্রযুক্তি, ডাটাবেস, নিরাপত্তা এবং ডেমো লগইন তথ্য দেওয়া আছে।',
    videoText: 'একটি ছোট ভিডিওতে লগইন, ছয়টি মিশন, ক্যাপ্টেন বোর্ড এবং তিন-স্ট্রাইক দেখান।',
    rowM1: 'রোল লগইন, অভিযোগ ফর্ম এবং X/3 স্ট্রাইক বার',
    rowM2: 'নাম/রোল/উচ্চতা ইনপুট এবং N × M উচ্চতা-সাজানো ডেস্ক গ্রিড',
    rowM3: 'LLM API দিয়ে বুলেট আকারে পরিষ্কার সিলেবাস',
    rowM4: 'গোপন টাকা/টিফিন লেজার এবং সময়ভিত্তিক চার্ট',
    rowM5: 'মোবাইল SOS, লোকেশন ড্রপডাউন এবং ক্যাপ্টেন ড্যাশবোর্ড',
    rowM6: 'সংরক্ষিত নিয়মে স্ট্রিং-ম্যাচিং অনুসন্ধান',
    rowDocs: 'সেটআপ, আর্কিটেকচার, সিদ্ধান্ত এবং screenshot-সহ README',
    rowSubmit: 'GitHub repository এবং রেকর্ড করা walkthrough',
    pwaReady: 'ইনস্টলযোগ্য মোবাইল PWA',
    pwaReadyText: 'Chrome থেকে ইনস্টল করে আলাদা মোবাইল অ্যাপের মতো ব্যবহার করা যাবে।',
    offlineReady: 'অফলাইন SOS কিউ',
    offlineReadyText: 'নেটওয়ার্ক না থাকলে গুরুত্বপূর্ণ SOS স্থানীয়ভাবে সংরক্ষিত হয়।',
    bilingualReady: 'বাংলা ও ইংরেজি',
    bilingualReadyText: 'ব্যবহারকারী যেকোনো সময় পুরো ইন্টারফেসের ভাষা বদলাতে পারে।',
    themeReady: 'লাইট ও ডার্ক থিম',
    themeReadyText: 'নির্বাচিত থিম ডিভাইসে মনে রাখা হয়।'
  }
};

function interpolate(text, vars = {}) {
  return String(text).replace(/\{(\w+)\}/g, (_match, key) => vars[key] ?? `{${key}}`);
}

function resolveTheme(theme) {
  if (theme !== 'system') return theme;
  return window.matchMedia?.('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
}

export function AppSettingsProvider({ children }) {
  const [language, setLanguageState] = useState(() => localStorage.getItem('ak_language') || 'en');
  const [theme, setThemeState] = useState(() => localStorage.getItem('ak_theme') || 'light');
  const [resolvedTheme, setResolvedTheme] = useState(() => resolveTheme(localStorage.getItem('ak_theme') || 'light'));

  useEffect(() => {
    localStorage.setItem('ak_language', language);
    document.documentElement.lang = language === 'bn' ? 'bn' : 'en';
    document.title = language === 'bn' ? 'অ্যান্টি-কুদ্দুস প্রোটোকল' : 'Anti-Kuddus Protocol';
  }, [language]);

  useEffect(() => {
    localStorage.setItem('ak_theme', theme);
    const media = window.matchMedia?.('(prefers-color-scheme: dark)');
    const apply = () => {
      const next = resolveTheme(theme);
      setResolvedTheme(next);
      document.documentElement.dataset.theme = next;
      document.querySelector('meta[name="theme-color"]')?.setAttribute('content', next === 'dark' ? '#09150f' : '#10231a');
    };
    apply();
    media?.addEventListener?.('change', apply);
    return () => media?.removeEventListener?.('change', apply);
  }, [theme]);

  const value = useMemo(() => ({
    language,
    setLanguage: (next) => setLanguageState(next === 'bn' ? 'bn' : 'en'),
    toggleLanguage: () => setLanguageState((current) => current === 'en' ? 'bn' : 'en'),
    theme,
    setTheme: (next) => setThemeState(['light', 'dark', 'system'].includes(next) ? next : 'light'),
    resolvedTheme,
    t: (key, vars) => interpolate(messages[language]?.[key] ?? messages.en[key] ?? key, vars)
  }), [language, theme, resolvedTheme]);

  return <AppSettingsContext.Provider value={value}>{children}</AppSettingsContext.Provider>;
}

export function useAppSettings() {
  const value = useContext(AppSettingsContext);
  if (!value) throw new Error('useAppSettings must be used inside AppSettingsProvider.');
  return value;
}
